import type { Org } from "./types";

export const DEMO_ORGS: Org[] = [
  {
    id: "humanity-project",
    name: "The Humanity Project",
    address: "449 St George St, Moncton, NB",
    phone: "(506) 382-6840",
    lat: 46.0927,
    lng: -64.7838,
    locationLabel: "Downtown Moncton",
    tags: ["food", "adult clothing", "community support"],
    items: [
      { id: "banana", quantity: 40, name: "Banana", image: "🍌", category: "food" },
      { id: "granola-bars", quantity: 60, name: "Granola Bars", image: "🥣", category: "food" },
      { id: "adult-socks", quantity: 80, name: "Adult Socks", image: "🧦", category: "clothing" },
      { id: "winter-gloves", quantity: 25, name: "Winter Gloves", image: "🧤", category: "clothing" },
      { id: "toothbrushes", quantity: 50, name: "Toothbrushes", image: "🪥", category: "hygiene" },
    ],
  },
  {
    id: "house-of-nazareth",
    name: "House of Nazareth",
    address: "75 Albert St, Moncton, NB",
    phone: "(506) 858-5702",
    lat: 46.0879,
    lng: -64.7865,
    locationLabel: "Central Moncton",
    tags: ["shelter", "meals", "clothing", "hygiene"],
    items: [
      { id: "water-bottles", quantity: 100, name: "Water Bottles", image: "💧", category: "food" },
      { id: "blankets", quantity: 20, name: "Blankets", image: "🛏️", category: "supplies" },
      { id: "hoodies", quantity: 18, name: "Hoodies", image: "👕", category: "clothing" },
      { id: "soap", quantity: 35, name: "Soap", image: "🧼", category: "hygiene" },
      { id: "shampoo", quantity: 30, name: "Shampoo", image: "🧴", category: "hygiene" },
    ],
  },
  {
    id: "ymca-reconnect",
    name: "YMCA ReConnect Outreach",
    address: "473 St George St, Moncton, NB",
    phone: "(506) 856-4362",
    lat: 46.0938,
    lng: -64.7829,
    locationLabel: "St. George Street",
    tags: ["outreach", "seasonal clothing", "footwear", "hygiene"],
    items: [
      { id: "snack-packs", quantity: 45, name: "Snack Packs", image: "🥪", category: "food" },
      { id: "backpacks", quantity: 14, name: "Backpacks", image: "🎒", category: "supplies" },
      { id: "boots", quantity: 16, name: "Boots", image: "🥾", category: "clothing" },
      { id: "coats", quantity: 12, name: "Coats", image: "🧥", category: "clothing" },
      { id: "deodorant", quantity: 28, name: "Deodorant", image: "🧴", category: "hygiene" },
    ],
  },
  {
    id: "harvest-house",
    name: "Harvest House Atlantic",
    address: "182 High St, Moncton, NB",
    phone: "(506) 855-0626",
    lat: 46.0824,
    lng: -64.7828,
    locationLabel: "High Street",
    tags: ["shelter", "hot meals", "housing support"],
    items: [
      { id: "apples", quantity: 35, name: "Apples", image: "🍎", category: "food" },
      { id: "protein-bars", quantity: 55, name: "Protein Bars", image: "🍫", category: "food" },
      { id: "tshirts", quantity: 26, name: "T-Shirts", image: "👕", category: "clothing" },
      { id: "underwear", quantity: 40, name: "Underwear", image: "🩲", category: "clothing" },
      { id: "toothpaste", quantity: 32, name: "Toothpaste", image: "🪥", category: "hygiene" },
    ],
  },
];